name: Validação de Ambiente
on:
  workflow_dispatch:
    inputs:
      versao:
        type: number
        required: true
        default: 1
jobs:
  call-build-e-testes:
    uses: ./.github/workflows/2-build-e-testes.yml
    with:
      versao: ${{ inputs.versao }}