name: Teste de ID
on: workflow_dispatch

jobs:
  build: # JOB ID = build
    runs-on: ubuntu-latest
    steps:
      - name: Teste de cobertura
        id: teste-cobertura # STEP ID = teste-cobertura
        run: echo "porcentagem=87" >> "$GITHUB_OUTPUT"
    outputs:
      teste-cobertura: ${{ steps.teste-cobertura.outputs.porcentagem }}

  quality-gate: # JOB ID = quality-gate
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Quality Gate Tests
        env:
          TESTE-COBERTURA: ${{ needs.build.outputs.teste-cobertura }}
        run: |
          echo "Cobertura mínima 80%"
          echo "Cobertura obtida: $TESTE-COBERTURA%"
          if (( $TESTE-COBERTURA < 80 )); then
            echo "::error::Build reprovado por baixa cobertura"
            exit 1
          fi