name: Valida o ambiente
on:
  workflow_dispatch:
jobs:
  valida-ambiente-prod:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment: production
    env:
      AMBIENTE: ${{ vars.AMBIENTE }}
    steps:
      - name: Printa valor ambiente
        run: echo "Estou no ambiente de $AMBIENTE" 

  valida-ambiente-staging:
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    environment: staging
    env:
      AMBIENTE: ${{ vars.AMBIENTE }}
    steps:
      - name: Printa valor ambiente
        run: echo "Estou no ambiente de $AMBIENTE".